workflows:
  android-native-release:
    name: Build Android Native Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        JAVA_VERSION: 17
      android:
        image: default
    scripts:
      - name: Configurar ambiente
        script: |
          export JAVA_HOME=$(/usr/libexec/java_home -v 17)
          export PATH=$JAVA_HOME/bin:$PATH
          echo "Usando Java 17 em $JAVA_HOME"
      - name: Limpar projeto
        script: ./gradlew clean
      - name: Compilar APK de release
        script: ./gradlew assembleRelease
      - name: Compilar AAB de release
        script: ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - seuemail@dominio.com
        notify:
          success: true
          failure: true
