workflows:
  android-native-release:
    name: Build Android Native Release APK and AAB
    max_build_duration: 60
    instance_type: linux_x2  # mais rápido e mais barato que mac_mini
    environment:
      vars:
        GRADLE_TASK: assembleRelease
        AAB_TASK: bundleRelease
        JAVA_VERSION: 17
        ANDROID_SDK_ROOT: /opt/android-sdk-linux
    scripts:
      - name: Configurar Java e Android SDK
        script: |
          sdkmanager --update || true
          sdkmanager "platforms;android-33" "build-tools;33.0.2"
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export PATH=$JAVA_HOME/bin:$PATH
      - name: Limpar projeto
        script: ./gradlew clean
      - name: Compilar APK de release
        script: ./gradlew $GRADLE_TASK
      - name: Compilar App Bundle (AAB)
        script: ./gradlew $AAB_TASK
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - seuemail@dominio.com
        notify:
          success: true
          failure: true
