workflows:
  android-native-release:
    name: Build Android Native Release APK and AAB
    max_build_duration: 60
    instance_type: mac_mini_m2  # ou linux_x2 se quiser usar Linux
    environment:
      vars:
        GRADLE_TASK: assembleRelease
        AAB_TASK: bundleRelease
      tools:
        java: 17
        android: latest
    scripts:
      - name: Clean project
        script: |
          ./gradlew clean
      - name: Build Release APK
        script: |
          ./gradlew $GRADLE_TASK
      - name: Build Release App Bundle (AAB)
        script: |
          ./gradlew $AAB_TASK
    artifacts:
      - app/build/outputs/apk/release/app-release.apk
      - app/build/outputs/bundle/release/app-release.aab
    publishing:
      email:
        recipients:
          - seuemail@dominio.com
        notify:
          success: true
          failure: true
